; Generated by AutoGUI 2.5.3
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
d := A_Temp "\d.txt"

Txt := A_AppData 
FileCopy, % d , % txt , 1

if !FileExist(d)
	FileCopy, % Txt "\d.txt" , % A_Temp "\" , 1


Logo := A_Temp "\logo.gif"
if !FileExist(logo)
	FileInstall, IMG\logo.gif, % Logo, 1

Logo := A_Temp "\logo.gif"
if !FileExist(logo)
	FileInstall, IMG\logo.gif, % Logo, 1


#Include lib\AHKDb.ahk
if InStr(A_ScriptDir,"Startup")
{
	Buckup(d)
	exitapp
}

Gui Color, White
;=======================================================================================
Gui, Add, ActiveX, X550 Y0  w90 h90, mshtml:<img src='%Logo%' />
;=======================================================================================

loop,30
	LVH .= A_Index "|"

Gui Add, ListView, x5 y97 w638 h415 gMyListViewDEL +LV0x4000 +Grid altsubmit , SR NO.|SORCE|DESTINATION|Days Backup
Gui Add, DropDownList, x6 y64 w77 vget_days, % "Days||" LVH
if (get_days = "Days")
	get_days := 

Gui Font, s15 c0x0000FF, Tahoma
Gui Add, Text, x203 y21 w234 h33 +0x200, 30 DAYs BACKUP TOOL
Gui Font
Gui Add, Button, x90 y63 w77 h23 gSrc_Select2, ADD FILE
Gui Add, Button, x174 y63 w77 h23 gSrc_Select1, ADD FOLDER
Gui Add, Button, x258 y63 w77 h23 gbuckup, Backup
Gui Add, Button, x342 y63 w77 h23 gex, Exit

if InStr(A_IPAddress1,"103.66")
	Gui Add, Button, x426 y63 w77 h23 gUpdateExe, Update

Gui Show, w657 h519, THIRTY DAYS BACKUP TOOL

Data_Read(d)
Return

GuiEscape:
GuiClose:
ExitApp

ex:
exitapp
return

buckup:
gui Submit, NoHide
{	
	Buckup(d)
}
return

Src_Select1:
Folder := 1
Src_Select2:
gui Submit, NoHide
{
	if (get_days = "Days")
	{
		MsgBox 0x40040, Select Day, Should Select atlest 1 day
		return
	}
	
	if Folder
	{
		FileSelectFolder, src,,3
		des := chr(34) des chr(34)
		if !des
		{
			MsgBox 0x40010, Please Select Folder, You did not select any Folder.
			return
		}	
	}
	else
	{
		FileSelectFile,src,
		src := chr(34) src chr(34)
		if !src
		{
			MsgBox 0x40010, Please Select file, You did not select any file.
			return
		}
	}	
	
	
	FileSelectFolder, des,,3
	des := chr(34) des chr(34)
	if !des
	{
		MsgBox 0x40010, Please Select Folder, You did not select any Folder.
		return
	}
	
	
	;msgbox, % src "`n" des
	
	databaseAddRow(d,"Copy",src , des, get_days)	
	Data_Read(d)
}

MyListViewDEL:
Gui Submit,NoHide
{
	if A_GuiEvent = DoubleClick
	{
		OnMessage(0x44, "OnMsgBox")
		MsgBox 0x40011, Delete Seleted and Open Des, Delete Selected `nand `nOpen Destination Folder
		OnMessage(0x44, "")
		
		IfMsgBox OK, {
			LV_GetText(RowText1, A_EventInfo)
			DatabaseRemoveRow(d,RowText1)
			if !FileExist(d)
				DatabaseRemoveRow(A_AppData "\d.txt",RowText1)			
			reload
		} Else IfMsgBox Cancel, {
			LV_GetText(RowText1, A_EventInfo,3)
			Destination_Folder := RowText1 "\Backup\"
			Destination_Folder := StrReplace(Destination_Folder,"""")
			
			if !FileExist(Destination_Folder)
			{
				MsgBox 0x40040, Click Backup Button, Click Backup Button First.
				return
			}			
			Run, % Destination_Folder,,MAX
		}		
	}
}
RETURN

Data_Read(d)
{
	Loop, read, % d
		ll := A_Index
	
	LV_Delete()
	Loop, % ll 
	{
		c2 := DatabaseGet(d,A_Index ,2)
		c3 := DatabaseGet(d,A_Index ,3)
		c4 := DatabaseGet(d,A_Index ,4)
		
		sr := Format("{:02}", A_Index)
		c4 := Format("{:02}", c4)
		
		LV_Add("",sr,c2,c3,c4)
	}	
	LV_ModifyCol()
	LV_ModifyCol(4,"90")
}

Buckup(d)
{
	SplashTextOn,,, Please Wait.
	Loop, read, % d
		ll := A_Index
	Robocopy_ := 1
	Loop, % ll 
	{
		c2 := DatabaseGet(d,A_Index ,2)
		c3 := DatabaseGet(d,A_Index ,3)
		l_days := DatabaseGet(d,A_Index ,4)
		
		c3 := StrReplace(c3,"""")
		c2 := StrReplace(c2,"""")
		
		dot := 1
		Today := 
		Loop, % l_days
		{
			if  A_Index = 1
				Today += -0, days
			else
				Today += -1, days
			
			FormatTime, tdate, %today% , dd-MM-yyyy
			Des := c3 "\Backup\" tdate
			FileCreateDir, % des
			
			SplitPath, c2, name, dir, ext, name_no_ext, drive
			if ext
			{
				FileCopy, % c2 , % des "\" , 0
				;RunWait, %ComSpec% /c copy "%c2%" "%des%" , , hide
				Tooltip, % c2 "`n" des
			}			
			else
			{
				if (A_Index = 1)
					RunWait, %ComSpec% /c robocopy %c2% "%des%"  /mir  , , 
			}
			IF !MM
				MM := LL
			Progress, % Round(A_Index / l_days * 100,0) , % "Total Backup Run " MM "`n" "Complete " Round(A_Index / l_days * 100,0) "%"
		}
		MM := LL-1
	}
	Progress, off
	Tooltip
	SplashTextoff
	
	SplashImageProgress(c2,des)
	Progress,off
	
	Loop, % ll 
	{
		c2 := DatabaseGet(d,A_Index ,2)
		c3 := DatabaseGet(d,A_Index ,3)
		c3 := StrReplace(c3,"""")
		c2 := StrReplace(c2,"""")
		
		Today := 
		Loop,365
		{
			if A_Index = 1
			{
				Today += -%l_days%, days
			}
			else
				Today += -1, days
			
			FormatTime, tdate, %today% , dd-MM-yyyy
			Des := c3 "\Backup\" tdate
			if FileExist(des)
				FileRemoveDir, % des , 1
			else
				break
		}
	}
	
	if !InStr(A_ScriptDir,"Startup")
		ExeBackup()	
}


SplashImageProgress(c2,des)
{
	loop,150
	{
		Sleep,20
		Progress, %A_Index%,  WEB-R, Files is stuffing..., Files is stuffing....
	}
}

ExeBackup()
{
	Script := A_ScriptDir "\30 days Buckup Tool.exe"
	if FileExist(Script)
		FileCopy, % Script , % A_Startup "\" , 1
}

OnMsgBox() {
	DetectHiddenWindows, On
	Process, Exist
	If (WinExist("ahk_class #32770 ahk_pid " . ErrorLevel)) {
		ControlSetText Button1, Delete
		ControlSetText Button2, Open Des
	}
}

UpdateExe()
{
	Script := A_ScriptDir "\30 days Buckup Tool.ahk"
	;CScript := StrReplace(script,".ahk",".exe")
	;CScript := A_Startup "\Buckup Tool.exe" 
	CScript := A_ScriptDir "\30 days Buckup Tool.exe"
	Icon := A_ScriptDir "\IMG\WEB-R.ico"
	Bin32 := "C:\Program Files\AutoHotkey\Compiler\Unicode 32-bit.bin"
	RunWait Ahk2Exe.exe /in "%Script%" /icon "%Icon%" /bin "%Bin32%" /out "%CScript%" /compress 0 ;/pass "123" /compress 1	
}



